# GitHub CI build pipeline
name: Hand digit Recognition CI package builder and installer

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3.11.4
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if  [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Unit Tests and generate coverage report
      run: |
        pytest -n 2 -v --dist=loadscope
        pytest -n 2 --dist=loadscope --cov=. --cov-report=term --cov-report=html
    - name: Archive code coverage html report
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: htmlcov
    - name: Run package creation
      run: |
        python -m pip install --user --upgrade build
        python -m build
    - name: List contents of dist  # Debug step to list contents of the dist folder
      run: ls -l dist
    - name: Archive package
      uses: actions/upload-artifact@v4
      with:
        name: Hand-digit-Recognition
        path: dist


  install:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifact (Hand-digit-Recognition)
        uses: actions/download-artifact@v4
        with:
          name: Hand-digit-Recognition

      - name: Install package from artifact
        run: |
          pip install *.whl


