name: CI Pipeline

on:
  push:
    branches:
      - main   # Get triggered when there are pushes to the main branch
  pull_request:
    branches:
      - main   # Get triggered when there are pull requests targeting the main branch

jobs:
  pre-commit-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run pre-commit
        run: |
           pre-commit run --all-files
     
  unit-tests:
    name: Unit tests 
    runs-on: ubuntu-latest
    needs: pre-commit-lint

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run unit tests
        run: |
          pytest test_home_route_sierra.py test_predict_result_hang.py test_prediction_route_sudhan.py test_preprocess_img_saba.py --maxfail=5 --disable-warnings

  happy-sad-path-tests:
    name: Happy and Sad Path Tests 
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run happy and sad path tests
        run: |
          pytest test_integration_happy_path_saba.py test_integration_sad_path_hang.py --maxfail=5 --disable-warnings

  acceptance-tests:
    name: Acceptance Tests 
    runs-on: ubuntu-latest
    needs: happy-sad-path-tests

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run acceptance tests
        run: |
          pytest test_acceptance_predict_hang.py test_acceptance_test_saba.py --disable-warnings
